# Generated by Django 4.1.5 on 2026-05-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view_type', models.CharField(choices=[('first_project', 'Premier projet'), ('project', 'Projet spécifique'), ('label', 'Étiquette spécifique')], default='first_project', max_length=20)),
                ('default_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.label')),
                ('default_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Paramètres',
            },
        ),
    ]
