# Generated by Django 4.1.5 on 2026-06-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
